### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by warmsunbeam** [HSAnet/open5gs-ui#3]
Hi HSAnet team,
   I am new to Python scripts. When I run your script with running open5gs system, I got the following error:
$ sudo python3 main.py
Traceback (most recent call last):
  File "/home/ui/proj/open5gs-ui-main/build/lib/app/main.py", line 7, in <module>
    from utils import start_logger, stop_logger, worker_config, LOG_QUEUE, ArgsException, e_print
  File "/home/ui/proj/open5gs-ui-main/build/lib/app/utils/__init__.py", line 5, in <module>
    from .open5g_rake import *
  File "/home/ui/proj/open5gs-ui-main/build/lib/app/utils/open5g_rake/__init__.py", line 1, in <module>
    from .rake import Open5gsException, Open5GRake
  File "/home/ui/proj/open5gs-ui-main/build/lib/app/utils/open5g_rake/rake.py", line 60
    return f'{{\"services\": {{\"service": [{','.join([service.to_json(time_delta) for service in self.__service_list])}]}}}}'
                                              ^
SyntaxError: f-string: expecting '}'

**Comment by warmsunbeam** [comment]
I think my python version 3.10 is default one on Ubuntu 22.04. I should use 3.12 instead to make it working according to its document section for client app.

**Comment by warmsunbeam** [comment]
Let me close this issue.
